### ISSUE TITLE
make a logo

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/wally#17]
just create a logo and put it at the top of the readme.md .

**Comment by madhavchoudhary0911** [comment]
I would like to work on this issue under JWOC

**Comment by Shreyan-12345** [comment]
i want to wok plz

**Comment by Ankit62042** [comment]
I want to work on this issue

**Comment by shibam-naskar** [comment]
> i want to wok plz

okk shreyan you are assigned for this issue

**Comment by binayshaw7777** [comment]
I want to work this issue under JWOC.

If the current assignees fails to complete it. Please sign me
