### ISSUE TITLE
Add a button over full screen image view . on tap open a popup.

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/wally#2]
add the button over the full screen image and name the button "set as wallpaper"

in the full screen image view page place a popup dialogue box on tap of the "set as wallpaper" button . on the dialogue box place a text "Set As Home Screen" and place two buttons bellow one is "OK" other one is "CANCEL"

**Comment by AmarjitM13** [comment]
I want to work on this issue under JWOC

**Comment by Poulami2515** [comment]
I would like to contribute to this issue.

**Comment by sahilrik** [comment]
i would like to contribute to this

**Comment by gargshruti** [comment]
I want to work on this issue under JWOC

**Comment by Nimishavashistha** [comment]
I would like to contribute on this issue under JWOC

**Comment by shibam-naskar** [comment]
> I want to work on this issue under JWOC

Awasome work @AmarjitM13
