### ISSUE TITLE
On cancel button tap pop the dialogue box.

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/wally#3]
in the dialogue box of full screen image view page just pop the context of the popup dialogue box when the "CANCEL" button is pressed.

**Comment by AmarjitM13** [comment]
I want to work on this issue under JWOC

**Comment by Poulami2515** [comment]
I would like to contribute to this issue.

**Comment by gargshruti** [comment]
I want to work on this issue under JWOC

**Comment by Nimishavashistha** [comment]
I want to work on this issue under JWOC
