### ISSUE TITLE
fetch images as per query from user.

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/wally#5]
in the home page when user enters some queries in the search bar fetch images according to the query . without any search button . just call the search function when search field controller value is changed.

**Comment by madhavchoudhary0911** [comment]
I want to work on this issue under JWOC

**Comment by sahilrik** [comment]
i wolud like to work on this

**Comment by gargshruti** [comment]
I want to work on this issue under JWOC

**Comment by Nimishavashistha** [comment]
I want to work on this issue under JWOC
