### ISSUE TITLE
add favourites page

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/wally#8]
add any local no sql database in app like hive and then add a icon button on wallpapers to add to favourites . store all favourite images links in the database . make a separate page to show all the favourite images . also give user option to un favourite any image.

**Comment by madhavchoudhary0911** [comment]
### **I am willing to contribute by resolving #8 with the following changes and updates:**

1.  Integrate Hive.
2.  Add Heart option Icon to every Wallpaper on the home page.
3.  Store all favorite links in a different stack "Favourites" with an option to unfavourite them.
4.  Update UI to make it look more appealing to users.

**Comment by shibam-naskar** [comment]
updated

**Comment by AmarjitM13** [comment]
I want to work on this issue under JWOC

**Comment by Nimishavashistha** [comment]
I want to work on this issue under jwoc
